### ISSUE TITLE
npm start fresh project boilerplate gives JS error

### ISSUE THREAD

**Issue by budda** [rblopes/phaser-plus-template#2] opened 2015-12-13 21:59 UTC
After setting up a new project my browser is black and two errors in the console.

```
GET http://localhost:3000/game.js (404)
(index):62 Uncaught TypeError: Cannot read property 'init' of undefined(anonymous function) @ (index):62
```

**Comment by budda** [comment] 2015-12-13 22:10
```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:62 Uncaught TypeError: Cannot read property 'init' of undefined
```

There is no game.js in the static folder.

**Comment by rblopes** [comment] 2015-12-15 16:32
Since the problem is related to rblopes/generator-phaser-plus#9, and a fix was sorted out, I'm closing this issue now. Thanks again.

**Closed by rblopes** 2015-12-15 16:32 UTC
